// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EF_Day3.Models;

public partial class Category
{
    public int CategoryID { get; set; }

    public string CategoryName { get; set; }

    public string DescriptionCat { get; set; }

    public virtual ICollection<Product> Products { get; set; } = new List<Product>();
}