// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EF_Day3.Models;

public partial class OrderItem
{
    public int OrderItemID { get; set; }

    public int? OrderID { get; set; }

    public int? ProductID { get; set; }

    public int? Quantity { get; set; }

    public decimal? Price { get; set; }

    public virtual Order Order { get; set; }

    public virtual Product Product { get; set; }
}